import { describe, expect, it } from "vitest";

import { getCurrentSection, getPromptSections } from "@/features/editor/parsePromptSections";

describe("prompt outline", () => {
  it("finds standalone custom and built-in tags with their original text positions", () => {
    const text =
      "Introduction\n  <TASK>\nDo this\n  </TASK>\n\n<custom-note>\nDetails\n</custom-note>";
    const sections = getPromptSections(text);

    expect(sections.map(({ name, line, depth }) => ({ name, line, depth }))).toEqual([
      { name: "TASK", line: 2, depth: 0 },
      { name: "custom-note", line: 6, depth: 0 },
    ]);
    expect(sections[0].start).toBe(text.indexOf("<TASK>"));
    expect(sections[0].contentStart).toBe(text.indexOf("Do this"));
    expect(sections[0].end).toBe(text.indexOf("</TASK>") + "</TASK>".length);
    expect(sections[1].contentStart).toBe(text.indexOf("Details"));
  });

  it("tracks the deepest current section and distinguishes repeated names", () => {
    const text =
      "<TASK>\nBefore\n<NOTE>\nFirst\n</NOTE>\n<NOTE>\nSecond\n</NOTE>\nAfter\n</TASK>\nOutside";
    const sections = getPromptSections(text);

    expect(sections.map((section) => section.depth)).toEqual([0, 1, 1]);
    expect(getCurrentSection(sections, text.indexOf("Before"))).toBe(sections[0]);
    expect(getCurrentSection(sections, text.indexOf("First"))).toBe(sections[1]);
    expect(getCurrentSection(sections, text.indexOf("Second"))).toBe(sections[2]);
    expect(getCurrentSection(sections, text.indexOf("After"))).toBe(sections[0]);
    expect(getCurrentSection(sections, text.indexOf("Outside"))).toBeUndefined();
  });

  it("ignores inline tags, attributes, and tags inside backtick or tilde code fences", () => {
    const text = [
      "Use <TASK> for a task.",
      '<div class="example">',
      "<EXAMPLE>",
      "````xml",
      "<IGNORED>",
      "```",
      "<STILL_IGNORED>",
      "````",
      "~~~",
      "<ALSO_IGNORED>",
      "~~~",
      "</EXAMPLE>",
      "<REAL>",
      "Text",
      "</REAL>",
    ].join("\n");

    expect(getPromptSections(text).map((section) => section.name)).toEqual(["EXAMPLE", "REAL"]);
  });

  it("keeps incomplete sections navigable while typing", () => {
    const text = "<TASK>\nWorking\n<NOTE>";
    const sections = getPromptSections(text);

    expect(sections).toHaveLength(2);
    expect(sections[1].contentStart).toBe(text.length);
    expect(getCurrentSection(sections, text.length)).toBe(sections[1]);
    expect(getPromptSections("<TAS")).toEqual([]);
  });

  it("recovers from missing inner closing tags without nesting following sections", () => {
    const text = "</UNKNOWN>\n<TASK>\n<NOTE>\nUnfinished\n</TASK>\n<OUTPUT>\nResult\n</OUTPUT>";
    const sections = getPromptSections(text);

    expect(sections.map(({ name, depth }) => ({ name, depth }))).toEqual([
      { name: "TASK", depth: 0 },
      { name: "NOTE", depth: 1 },
      { name: "OUTPUT", depth: 0 },
    ]);
    expect(getCurrentSection(sections, text.indexOf("</TASK>"))).toBe(sections[0]);
    expect(getCurrentSection(sections, text.indexOf("Result"))).toBe(sections[2]);
  });

  it("preserves positions for indented CRLF text", () => {
    const text = "\r\n\t<CUSTOM>\r\nBody\r\n\t</CUSTOM>\r\n";
    const [section] = getPromptSections(text);

    expect(section.line).toBe(2);
    expect(section.contentStart).toBe(text.indexOf("Body"));
    expect(section.start).toBe(text.indexOf("<CUSTOM>"));
  });

  it("supports tag names beginning with numbers, as generated by custom tag insertion", () => {
    const [section] = getPromptSections("<2026_PLAN>\nPlan\n</2026_PLAN>");
    expect(section.name).toBe("2026_PLAN");
    expect(section.contentStart).toBe(12);
  });
});
